"""add audit logs

Revision ID: 4ea82d3234c3
Revises: 0004_create_spending
Create Date: 2026-05-23 16:03:21.423026
"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "4ea82d3234c3"
down_revision = "0004_create_spending"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("module", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_entity_id"), "audit_logs", ["entity_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_public_id"), "audit_logs", ["public_id"], unique=True)
    op.create_index(op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_workspace_id"), "audit_logs", ["workspace_id"], unique=False
    )
    op.drop_constraint(op.f("auth_sessions_public_id_key"), "auth_sessions", type_="unique")
    op.drop_constraint(op.f("auth_sessions_sid_key"), "auth_sessions", type_="unique")
    op.drop_index(op.f("ix_auth_sessions_public_id"), table_name="auth_sessions")
    op.create_index(op.f("ix_auth_sessions_public_id"), "auth_sessions", ["public_id"], unique=True)
    op.drop_index(op.f("ix_auth_sessions_sid"), table_name="auth_sessions")
    op.create_index(op.f("ix_auth_sessions_sid"), "auth_sessions", ["sid"], unique=True)
    op.create_index(
        op.f("ix_spending_budgets_category_id"), "spending_budgets", ["category_id"], unique=False
    )
    op.create_foreign_key(None, "spending_budgets", "spending_categories", ["category_id"], ["id"])
    op.create_index(
        op.f("ix_spending_transactions_user_id"), "spending_transactions", ["user_id"], unique=False
    )
    op.create_foreign_key(
        None, "spending_transactions", "spending_categories", ["category_id"], ["id"]
    )
    op.drop_constraint(op.f("todos_public_id_key"), "todos", type_="unique")
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.drop_constraint(op.f("users_public_id_key"), "users", type_="unique")
    op.drop_constraint(op.f("users_username_key"), "users", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_index(op.f("ix_users_public_id"), table_name="users")
    op.create_index(op.f("ix_users_public_id"), "users", ["public_id"], unique=True)
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.drop_constraint(op.f("workspaces_public_id_key"), "workspaces", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("workspaces_public_id_key"),
        "workspaces",
        ["public_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.drop_index(op.f("ix_users_public_id"), table_name="users")
    op.create_index(op.f("ix_users_public_id"), "users", ["public_id"], unique=False)
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint(
        op.f("users_username_key"), "users", ["username"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("users_public_id_key"), "users", ["public_id"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("todos_public_id_key"), "todos", ["public_id"], postgresql_nulls_not_distinct=False
    )
    op.drop_constraint(None, "spending_transactions", type_="foreignkey")
    op.drop_index(op.f("ix_spending_transactions_user_id"), table_name="spending_transactions")
    op.drop_constraint(None, "spending_budgets", type_="foreignkey")
    op.drop_index(op.f("ix_spending_budgets_category_id"), table_name="spending_budgets")
    op.drop_index(op.f("ix_auth_sessions_sid"), table_name="auth_sessions")
    op.create_index(op.f("ix_auth_sessions_sid"), "auth_sessions", ["sid"], unique=False)
    op.drop_index(op.f("ix_auth_sessions_public_id"), table_name="auth_sessions")
    op.create_index(
        op.f("ix_auth_sessions_public_id"), "auth_sessions", ["public_id"], unique=False
    )
    op.create_unique_constraint(
        op.f("auth_sessions_sid_key"), "auth_sessions", ["sid"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("auth_sessions_public_id_key"),
        "auth_sessions",
        ["public_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_audit_logs_workspace_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_public_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_entity_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
