"""add system key to todos

Revision ID: 1338de0c87a2
Revises: 4ea82d3234c3
Create Date: 2026-05-23 16:43:56.141786
"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "1338de0c87a2"
down_revision = "4ea82d3234c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "todos",
        sa.Column("system_key", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    )
    op.create_index(op.f("ix_todos_system_key"), "todos", ["system_key"], unique=False)
    op.create_unique_constraint(
        "uq_todo_workspace_system_key", "todos", ["workspace_id", "system_key"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_todo_workspace_system_key", "todos", type_="unique")
    op.drop_index(op.f("ix_todos_system_key"), table_name="todos")
    op.drop_column("todos", "system_key")
    # ### end Alembic commands ###
