"""add_workspace_membership_uniqueness

Revision ID: 95fd54bc02f7
Revises: 0018_user_finance_settings
Create Date: 2026-05-31 22:12:03.546704
"""

from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = "95fd54bc02f7"
down_revision = "0018_user_finance_settings"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_workspace_membership_workspace_user",
        "workspace_memberships",
        ["workspace_id", "user_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_workspace_membership_workspace_user", "workspace_memberships", type_="unique"
    )
    # ### end Alembic commands ###
